[package]
name = "use_priv_dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-lib = {git = "ssh://git@github.com/hornadam8/test-rust-private-dep.git"}


